import os
import re
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether
)


BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)

REPORTS_DIR = os.path.join(
    BASE_DIR,
    "reports"
)


# ============================================================
# MAIN REPORT GENERATOR
# ============================================================

def generate_report(data):

    os.makedirs(
        REPORTS_DIR,
        exist_ok=True
    )

    audit = data.get("audit", {})
    ai = data.get("ai", {})

    if not isinstance(audit, dict):
        audit = {}

    if not isinstance(ai, dict):
        ai = {}

    domain = audit.get(
        "domain",
        "Website"
    )

    safe_domain = re.sub(
        r"[^a-zA-Z0-9.-]",
        "_",
        str(domain)
    )

    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )

    filename = (
        f"SiteForge_Audit_"
        f"{safe_domain}_"
        f"{timestamp}.pdf"
    )

    filepath = os.path.join(
        REPORTS_DIR,
        filename
    )

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm
    )

    styles = create_styles()

    story = []

    # ========================================================
    # COVER
    # ========================================================

    story.append(
        Spacer(1, 22 * mm)
    )

    story.append(
        Paragraph(
            "SITEFORGE AI",
            styles["Brand"]
        )
    )

    story.append(
        Spacer(1, 8 * mm)
    )

    story.append(
        Paragraph(
            "WEBSITE AUDIT",
            styles["CoverTitle"]
        )
    )

    story.append(
        Paragraph(
            "AI-Powered Website Intelligence Report",
            styles["Subtitle"]
        )
    )

    story.append(
        Spacer(1, 16 * mm)
    )

    story.append(
        Paragraph(
            escape(domain),
            styles["Domain"]
        )
    )

    story.append(
        Spacer(1, 12 * mm)
    )

    overall = get_score(
        audit.get("scores", {}),
        "overall"
    )

    story.append(
        Paragraph(
            str(overall),
            styles["BigScore"]
        )
    )

    story.append(
        Paragraph(
            "OUT OF 100",
            styles["ScoreLabel"]
        )
    )

    health = ai.get(
        "health",
        get_health(overall)
    )

    story.append(
        Spacer(1, 7 * mm)
    )

    story.append(
        Paragraph(
            f"Website Health: {escape(health)}",
            styles["Health"]
        )
    )

    story.append(
        Spacer(1, 18 * mm)
    )

    generated = datetime.now().strftime(
        "%B %d, %Y at %H:%M"
    )

    story.append(
        Paragraph(
            f"Generated: {generated}",
            styles["Small"]
        )
    )

    story.append(
        Spacer(1, 3 * mm)
    )

    story.append(
        Paragraph(
            "Generated by SiteForge AI",
            styles["Small"]
        )
    )

    story.append(
        PageBreak()
    )

    # ========================================================
    # EXECUTIVE SUMMARY
    # ========================================================

    story.append(
        section_title(
            "1. Executive Summary",
            styles
        )
    )

    story.append(
        Paragraph(
            escape(
                ai.get(
                    "executive_summary",
                    "No executive summary available."
                )
            ),
            styles["Body"]
        )
    )

    story.append(
        Spacer(1, 7 * mm)
    )

    story.append(
        Paragraph(
            "Overall Assessment",
            styles["Subheading"]
        )
    )

    story.append(
        Paragraph(
            escape(
                ai.get(
                    "health_description",
                    "No assessment available."
                )
            ),
            styles["Body"]
        )
    )

    story.append(
        Spacer(1, 9 * mm)
    )

    # ========================================================
    # SCORE BREAKDOWN
    # ========================================================

    story.append(
        section_title(
            "2. Score Breakdown",
            styles
        )
    )

    scores = audit.get(
        "scores",
        {}
    )

    score_rows = [
        ["Category", "Score", "Assessment"],
        [
            "SEO",
            f"{get_score(scores, 'seo')}/100",
            assessment(
                get_score(scores, "seo")
            )
        ],
        [
            "Performance",
            f"{get_score(scores, 'performance')}/100",
            assessment(
                get_score(scores, "performance")
            )
        ],
        [
            "Accessibility",
            f"{get_score(scores, 'accessibility')}/100",
            assessment(
                get_score(scores, "accessibility")
            )
        ],
        [
            "Technical",
            f"{get_score(scores, 'technical')}/100",
            assessment(
                get_score(scores, "technical")
            )
        ],
        [
            "UX / Conversion",
            f"{get_score(scores, 'ux')}/100",
            assessment(
                get_score(scores, "ux")
            )
        ]
    ]

    story.append(
        make_table(
            score_rows,
            [55 * mm, 35 * mm, 55 * mm]
        )
    )

    story.append(
        Spacer(1, 10 * mm)
    )

    # ========================================================
    # BUSINESS IMPACT
    # ========================================================

    story.append(
        section_title(
            "3. Business Impact",
            styles
        )
    )

    impacts = ai.get(
        "business_impacts",
        []
    )

    if not isinstance(impacts, list):
        impacts = []

    for impact in impacts:

        if not isinstance(impact, dict):
            continue

        area = impact.get(
            "area",
            "Optimization"
        )

        description = impact.get(
            "impact",
            ""
        )

        story.append(
            Paragraph(
                f"<b>{escape(area)}</b>",
                styles["Subheading"]
            )
        )

        story.append(
            Paragraph(
                escape(description),
                styles["Body"]
            )
        )

        story.append(
            Spacer(1, 4 * mm)
        )

    # ========================================================
    # TOP OPPORTUNITIES
    # ========================================================

    story.append(
        section_title(
            "4. Top Opportunities",
            styles
        )
    )

    opportunities = ai.get(
        "top_opportunities",
        []
    )

    if not isinstance(opportunities, list):
        opportunities = []

    if not opportunities:

        story.append(
            Paragraph(
                "No major opportunities were detected.",
                styles["Body"]
            )
        )

    for index, opportunity in enumerate(
        opportunities[:8],
        start=1
    ):

        if not isinstance(opportunity, dict):
            continue

        category = opportunity.get(
            "category",
            "General"
        )

        issue = opportunity.get(
            "issue",
            "Issue detected"
        )

        priority = opportunity.get(
            "priority",
            "Medium"
        )

        recommendation = opportunity.get(
            "recommendation",
            "Review and address this finding."
        )

        impact = opportunity.get(
            "impact",
            ""
        )

        effort = opportunity.get(
            "effort",
            "Medium"
        )

        block = []

        block.append(
            Paragraph(
                f"<b>{index}. {escape(category)}</b> "
                f"<font size='8'>"
                f"[{escape(priority)} priority]"
                f"</font>",
                styles["OpportunityCategory"]
            )
        )

        block.append(
            Paragraph(
                f"<b>Finding:</b> "
                f"{escape(issue)}",
                styles["Body"]
            )
        )

        if impact:

            block.append(
                Paragraph(
                    f"<b>Business Impact:</b> "
                    f"{escape(impact)}",
                    styles["Body"]
                )
            )

        block.append(
            Paragraph(
                f"<b>Recommended Action:</b> "
                f"{escape(recommendation)}",
                styles["Body"]
            )
        )

        block.append(
            Paragraph(
                f"<b>Estimated Effort:</b> "
                f"{escape(effort)}",
                styles["Small"]
            )
        )

        block.append(
            Spacer(1, 5 * mm)
        )

        story.append(
            KeepTogether(block)
        )

    # ========================================================
    # TECHNICAL DETAILS
    # ========================================================

    story.append(
        PageBreak()
    )

    story.append(
        section_title(
            "5. Technical Website Details",
            styles
        )
    )

    technical_rows = [
        ["Metric", "Result"],

        [
            "Final URL",
            audit.get(
                "final_url",
                "-"
            )
        ],

        [
            "HTTP Status",
            audit.get(
                "status_code",
                "-"
            )
        ],

        [
            "Response Time",
            f"{audit.get('response_time', '-')}"
            f" seconds"
        ],

        [
            "Page Size",
            f"{audit.get('page_size_mb', '-')}"
            f" MB"
        ],

        [
            "HTTPS",
            yes_no(
                audit.get(
                    "https",
                    False
                )
            )
        ],

        [
            "Canonical URL",
            yes_no(
                audit.get(
                    "canonical_detected",
                    False
                )
            )
        ],

        [
            "Mobile Viewport",
            yes_no(
                audit.get(
                    "viewport_detected",
                    False
                )
            )
        ],

        [
            "robots.txt",
            yes_no(
                audit.get(
                    "robots_detected",
                    False
                )
            )
        ],

        [
            "Sitemap",
            yes_no(
                audit.get(
                    "sitemap_detected",
                    False
                )
            )
        ],

        [
            "Structured Data",
            audit.get(
                "structured_data_count",
                0
            )
        ],

        [
            "Images",
            audit.get(
                "images",
                0
            )
        ],

        [
            "Images Missing Alt",
            audit.get(
                "images_missing_alt",
                0
            )
        ],

        [
            "Total Links",
            audit.get(
                "links",
                0
            )
        ],

        [
            "Internal Links",
            audit.get(
                "internal_links",
                0
            )
        ],

        [
            "External Links",
            audit.get(
                "external_links",
                0
            )
        ],

        [
            "Word Count",
            audit.get(
                "word_count",
                0
            )
        ],

        [
            "Forms",
            audit.get(
                "forms",
                0
            )
        ],

        [
            "Buttons",
            audit.get(
                "buttons",
                0
            )
        ]
    ]

    story.append(
        make_table(
            technical_rows,
            [70 * mm, 75 * mm]
        )
    )

    # ========================================================
    # SOCIAL METADATA
    # ========================================================

    social = audit.get(
        "social_metadata",
        {}
    )

    if not isinstance(social, dict):
        social = {}

    story.append(
        Spacer(1, 9 * mm)
    )

    story.append(
        Paragraph(
            "Social Sharing Metadata",
            styles["Subheading"]
        )
    )

    social_rows = [
        [
            "Open Graph Title",
            yes_no(
                social.get(
                    "og_title",
                    False
                )
            )
        ],
        [
            "Open Graph Description",
            yes_no(
                social.get(
                    "og_description",
                    False
                )
            )
        ],
        [
            "Open Graph Image",
            yes_no(
                social.get(
                    "og_image",
                    False
                )
            )
        ]
    ]

    story.append(
        make_table(
            social_rows,
            [70 * mm, 75 * mm]
        )
    )

    # ========================================================
    # NEXT STEPS
    # ========================================================

    story.append(
        PageBreak()
    )

    story.append(
        section_title(
            "6. Recommended Next Steps",
            styles
        )
    )

    next_steps = ai.get(
        "next_steps",
        []
    )

    if not isinstance(next_steps, list):
        next_steps = []

    for index, step in enumerate(
        next_steps[:5],
        start=1
    ):

        if not isinstance(step, dict):
            continue

        category = step.get(
            "category",
            "Optimization"
        )

        score = step.get(
            "score",
            0
        )

        action = step.get(
            "action",
            ""
        )

        story.append(
            Paragraph(
                f"<b>{index}. "
                f"{escape(category)} "
                f"({score}/100)</b>",
                styles["Subheading"]
            )
        )

        story.append(
            Paragraph(
                escape(action),
                styles["Body"]
            )
        )

        story.append(
            Spacer(1, 5 * mm)
        )

    story.append(
        Spacer(1, 8 * mm)
    )

    story.append(
        Paragraph(
            "Recommended Strategy",
            styles["Subheading"]
        )
    )

    story.append(
        Paragraph(
            "Prioritize the highest-impact issues first. "
            "Addressing technical foundations, search visibility, "
            "performance, accessibility, and conversion friction "
            "can create a stronger foundation for sustainable growth.",
            styles["Body"]
        )
    )

    # ========================================================
    # BUILD PDF
    # ========================================================

    doc.build(
        story,
        onFirstPage=add_footer,
        onLaterPages=add_footer
    )

    return filepath


# ============================================================
# STYLES
# ============================================================

def create_styles():

    styles = getSampleStyleSheet()

    styles.add(
        ParagraphStyle(
            name="Brand",
            parent=styles["Normal"],
            fontSize=13,
            leading=16,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#6C63FF"),
            spaceAfter=6
        )
    )

    styles.add(
        ParagraphStyle(
            name="CoverTitle",
            parent=styles["Title"],
            fontSize=31,
            leading=36,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#111827")
        )
    )

    styles.add(
        ParagraphStyle(
            name="Subtitle",
            parent=styles["Normal"],
            fontSize=12,
            leading=16,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#6B7280")
        )
    )

    styles.add(
        ParagraphStyle(
            name="Domain",
            parent=styles["Heading2"],
            fontSize=19,
            leading=24,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#111827")
        )
    )

    styles.add(
        ParagraphStyle(
            name="BigScore",
            parent=styles["Title"],
            fontSize=58,
            leading=60,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#6C63FF")
        )
    )

    styles.add(
        ParagraphStyle(
            name="ScoreLabel",
            parent=styles["Normal"],
            fontSize=9,
            leading=12,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#6B7280")
        )
    )

    styles.add(
        ParagraphStyle(
            name="Health",
            parent=styles["Normal"],
            fontSize=12,
            leading=16,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#16A34A")
        )
    )

    styles.add(
        ParagraphStyle(
            name="Section",
            parent=styles["Heading1"],
            fontSize=17,
            leading=21,
            textColor=colors.HexColor("#111827"),
            spaceBefore=4,
            spaceAfter=8
        )
    )

    styles.add(
        ParagraphStyle(
            name="Subheading",
            parent=styles["Heading3"],
            fontSize=11,
            leading=15,
            textColor=colors.HexColor("#111827"),
            spaceBefore=3,
            spaceAfter=4
        )
    )

    styles.add(
        ParagraphStyle(
            name="Body",
            parent=styles["BodyText"],
            fontSize=9.5,
            leading=14,
            textColor=colors.HexColor("#374151"),
            spaceAfter=5
        )
    )

    styles.add(
        ParagraphStyle(
            name="Small",
            parent=styles["Normal"],
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#6B7280")
        )
    )

    styles.add(
        ParagraphStyle(
            name="OpportunityCategory",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#6C63FF"),
            spaceAfter=4
        )
    )

    return styles


# ============================================================
# SECTION TITLE
# ============================================================

def section_title(title, styles):

    return Paragraph(
        escape(title),
        styles["Section"]
    )


# ============================================================
# SCORE
# ============================================================

def get_score(scores, key):

    if not isinstance(scores, dict):
        return 0

    value = scores.get(
        key,
        0
    )

    try:
        return int(value)
    except:
        return 0


# ============================================================
# ASSESSMENT
# ============================================================

def assessment(score):

    if score >= 90:
        return "Excellent"

    if score >= 80:
        return "Good"

    if score >= 70:
        return "Needs Improvement"

    if score >= 50:
        return "Weak"

    return "Critical"


# ============================================================
# HEALTH
# ============================================================

def get_health(score):

    if score >= 90:
        return "Excellent"

    if score >= 80:
        return "Good"

    if score >= 70:
        return "Needs Improvement"

    if score >= 50:
        return "Weak"

    return "Critical"


# ============================================================
# YES / NO
# ============================================================

def yes_no(value):

    return "Detected" if value else "Not Detected"


# ============================================================
# TABLE
# ============================================================

def make_table(rows, widths):

    table = Table(
        rows,
        colWidths=widths,
        repeatRows=1
    )

    table.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.HexColor("#111827")
            ),

            (
                "TEXTCOLOR",
                (0, 0),
                (-1, 0),
                colors.white
            ),

            (
                "FONTNAME",
                (0, 0),
                (-1, 0),
                "Helvetica-Bold"
            ),

            (
                "FONTSIZE",
                (0, 0),
                (-1, -1),
                8.5
            ),

            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.35,
                colors.HexColor("#D1D5DB")
            ),

            (
                "ROWBACKGROUNDS",
                (0, 1),
                (-1, -1),
                [
                    colors.white,
                    colors.HexColor("#F9FAFB")
                ]
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),

            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                7
            ),

            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                7
            ),

            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                6
            ),

            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                6
            )
        ])
    )

    return table


# ============================================================
# FOOTER
# ============================================================

def add_footer(canvas, doc):

    canvas.saveState()

    canvas.setFont(
        "Helvetica",
        7
    )

    canvas.setFillColor(
        colors.HexColor("#9CA3AF")
    )

    canvas.drawString(
        18 * mm,
        10 * mm,
        "Generated by SiteForge AI"
    )

    canvas.drawRightString(
        A4[0] - 18 * mm,
        10 * mm,
        f"Page {doc.page}"
    )

    canvas.restoreState()


# ============================================================
# HTML ESCAPE
# ============================================================

def escape(value):

    value = str(value)

    return (
        value
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )